#!/usr/bin/env python3
# scripts/setup_server.py — One-time server initialization
# Generates JWT secret, server.env, and empty node_registry.json
import os
import sys
import json
import secrets
import argparse

# Add parent to path so we can import config if needed
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def main():
    parser = argparse.ArgumentParser(
        description="Initialize the FedBuff server (run once before starting)"
    )
    parser.add_argument(
        "--server-ip", type=str, default="0.0.0.0",
        help="Server bind IP (use 0.0.0.0 to listen on all interfaces)"
    )
    parser.add_argument(
        "--server-port", type=int, default=8765,
        help="Server port (default: 8765)"
    )
    parser.add_argument(
        "--aggregation-strategy", type=str, default="krum",
        choices=["fedavg", "trimmed_mean", "coordinate_median", "krum", "reputation", "staleness_aware"],
        help="Aggregation strategy (default: krum)"
    )
    parser.add_argument(
        "--max-nodes-per-task", type=int, default=10,
        help="Maximum number of nodes per FL task (default: 10)"
    )
    parser.add_argument(
        "--env-file", type=str, default="server.env",
        help="Output server env file (default: server.env)"
    )
    parser.add_argument(
        "--registry-file", type=str, default="./node_registry.json",
        help="Path to node registry JSON file (default: ./node_registry.json)"
    )
    parser.add_argument(
        "--force", action="store_true",
        help="Overwrite existing server.env (default: skip if exists)"
    )
    args = parser.parse_args()

    env_file = args.env_file

    # Idempotency check
    if os.path.exists(env_file) and not args.force:
        print(f"Server env file already exists: {env_file}")
        print("Use --force to regenerate (this will invalidate existing node tokens!)")
        return

    # Generate JWT secret
    jwt_secret = secrets.token_hex(32)
    print(f"Generated JWT secret: {jwt_secret[:16]}...")

    # Write server.env
    env_content = f"""# FedBuff Server Configuration
# Generated by scripts/setup_server.py
# WARNING: Changing JWT_SECRET invalidates all existing node tokens.

JWT_SECRET={jwt_secret}
NODE_REGISTRY_FILE={args.registry_file}
MAX_NODES_PER_TASK={args.max_nodes_per_task}

SERVER_HOST={args.server_ip}
SERVER_PORT={args.server_port}

AGGREGATION_STRATEGY={args.aggregation_strategy}
BUFFER_SIZE_K=3
MIN_UPDATES_FOR_AGGREGATION=2
MAX_WAIT_SECONDS=10.0
MAX_STALENESS=10
L2_NORM_THRESHOLD=500.0

MODEL_CHECKPOINT_DIR=./results/checkpoints
RESULTS_DIR=./results
LOG_LEVEL=INFO
"""
    with open(env_file, "w") as f:
        f.write(env_content)
    print(f"Written: {env_file}")

    # Initialize empty node registry
    registry_path = args.registry_file
    registry_dir = os.path.dirname(registry_path) or "."
    os.makedirs(registry_dir, exist_ok=True)

    if not os.path.exists(registry_path):
        registry_data = {
            "max_nodes_per_task": args.max_nodes_per_task,
            "task_counts": {},
            "nodes": {},
        }
        with open(registry_path, "w") as f:
            json.dump(registry_data, f, indent=2)
        print(f"Written: {registry_path}")
    else:
        print(f"Registry file already exists: {registry_path} (not overwritten)")

    print()
    print("=" * 60)
    print("Server setup complete!")
    print("=" * 60)
    print(f"  Start server:  uvicorn main:app --env-file {env_file}")
    print(f"  Add nodes:     python scripts/add_node.py --server-url http://localhost:{args.server_port} ...")
    print()
    print("IMPORTANT: Keep server.env secure — it contains the JWT secret.")


if __name__ == "__main__":
    main()
